services:

  wireguard:
    image: imzami/easyguard
    environment:
      - NAT=1
      - INTERFACE=eth0
      - PORT=55555
      - PUBLIC_IP=1.2.3.4
      - DNS=1.1.1.1,8.8.8.8
      - SUBNET_IP=10.88.0.1/16
      - CLIENTCONTROL_NO_LOGS=0
      - WG_CLIENTS_UNSAFE_PERMISSIONS=0
    volumes:
      - ./wireguard/:/etc/wireguard/
    ports:
      - 55555:55555/udp
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    restart: always
