name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: Login to Docker Hub using secrets
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ Step 3: Build Docker image and tag for Docker Hub
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag imzami/easygurd:latest

      # ✅ Step 4: Push image to Docker Hub
      - name: Push to Docker Hub
        run: docker push imzami/easygurd:latest
